import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const vazir = Vazirmatn({ subsets: ["latin"] });

export const metadata = {
  title: "food order test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={vazir.className}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
